---
name: PR Title
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - README.md

jobs:
  run:
    name: Check the Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@077bddd7bdabd0d2b1b25ed0754c7e62e184d7ee
        with:
          regex: '^(Add|Update|Remove)\s`.+\/.+`$'
          verbal_description: |
            Add|Update|Remove `username/repo`
          github_token: ${{ github.token }}
